# Generated by Django 5.2.2 on 2025-06-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perro',
            old_name='estado',
            new_name='estado_adopcion',
        ),
        migrations.AddField(
            model_name='perro',
            name='edad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perro',
            name='estado_salud',
            field=models.CharField(default='saludable', max_length=100),
        ),
        migrations.AddField(
            model_name='perro',
            name='peso',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='perro',
            name='tamaño',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='perro',
            name='vacunado',
            field=models.BooleanField(default=False),
        ),
    ]
