# Generated by Django 5.2.2 on 2025-06-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0002_rename_estado_perro_estado_adopcion_perro_edad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='raza',
            field=models.CharField(choices=[('labrador', 'Labrador'), ('caniche', 'Caniche'), ('bulldog', 'Bulldog'), ('ovejero', 'Ovejero'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
    ]
