# Generated by Django 5.2.2 on 2025-06-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0003_alter_perro_raza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='estado_salud',
            field=models.CharField(choices=[('saludable', 'Saludable'), ('herido', 'Herido'), ('enfermo', 'Enfermo'), ('enlasultimas', 'En las últimas'), ('recuperado', 'Recuperado')], default='saludable', max_length=20),
        ),
    ]
