# Generated by Django 5.2.2 on 2025-06-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0005_remove_usuarioadoptante_preferencia_mascota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='edad',
            field=models.CharField(choices=[('1', 'Cachorro'), ('2', 'Joven'), ('3', 'Adulto'), ('4', 'Viejo'), ('5', 'Indistinto')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='perro',
            name='estado_adopcion',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='perro',
            name='estado_salud',
            field=models.CharField(choices=[('1', 'Saludable'), ('2', 'Herido'), ('3', 'Enfermo'), ('4', 'En las últimas'), ('5', 'Recuperado')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='perro',
            name='raza',
            field=models.CharField(choices=[('1', 'Labrador'), ('2', 'Caniche'), ('3', 'Bulldog'), ('4', 'Ovejero'), ('5', 'Otro')], default='5', max_length=20),
        ),
        migrations.AlterField(
            model_name='perro',
            name='tamaño',
            field=models.CharField(choices=[('1', 'Chico'), ('2', 'Mediano'), ('3', 'Grande'), ('4', 'Gigante')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuarioadoptante',
            name='pref_edad',
            field=models.CharField(choices=[('1', 'Cachorro'), ('2', 'Joven'), ('3', 'Adulto'), ('4', 'Viejo'), ('5', 'Indistinto')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuarioadoptante',
            name='pref_estado_salud',
            field=models.CharField(choices=[('1', 'Saludable'), ('2', 'Herido'), ('3', 'Enfermo'), ('4', 'En las últimas'), ('5', 'Recuperado')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuarioadoptante',
            name='pref_raza',
            field=models.CharField(choices=[('1', 'Labrador'), ('2', 'Caniche'), ('3', 'Bulldog'), ('4', 'Ovejero'), ('5', 'Otro')], default='5', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuarioadoptante',
            name='pref_tamaño',
            field=models.CharField(choices=[('1', 'Chico'), ('2', 'Mediano'), ('3', 'Grande'), ('4', 'Gigante')], default='1', max_length=20),
        ),
    ]
