# Generated by Django 5.2.2 on 2025-06-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0006_alter_perro_edad_alter_perro_estado_adopcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='estado_adopcion',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('adoptado', 'Adoptado')], default='disponible', max_length=20),
        ),
    ]
