# Generated by Django 5.2.2 on 2025-06-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0007_alter_perro_estado_adopcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='estado_adopcion',
            field=models.CharField(choices=[('1', 'Disponible'), ('2', 'Adoptado')], default='disponible', max_length=20),
        ),
    ]
